### ISSUE TITLE
OSMC (verzió: 2020.11-1) + PI3 (típus: Pi 3 Model B Plus Rev 1.3) telepítés hiba

### ISSUE THREAD

**Issue by pappt** [szabbenjamin/digionline#54]
root@osmc:/home/osmc# wget -N https://raw.githubusercontent.com/szabbenjamin/digionline/master/osmc_installer.sh && bash osmc_installer.sh
--2021-04-29 08:59:15--  https://raw.githubusercontent.com/szabbenjamin/digionline/master/osmc_installer.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1408 (1.4K) [text/plain]
Saving to: 'osmc_installer.sh'

osmc_installer.sh                      100%[============================================================================>]   1.38K  --.-KB/s    in 0.001s

Last-modified header missing -- time-stamps turned off.
2021-04-29 08:59:15 (1.93 MB/s) - 'osmc_installer.sh' saved [1408/1408]

DIGIOnline v2 servlet telepito indul...
Hit:1 http://ftp.debian.org/debian buster InRelease
Get:2 http://ftp.debian.org/debian buster-updates InRelease [51.9 kB]
Hit:3 http://security.debian.org buster/updates InRelease
Hit:4 https://deb.nodesource.com/node_8.x stretch InRelease
Hit:5 http://ftp.fau.de/osmc/osmc/apt buster InRelease
Fetched 51.9 kB in 4s (12.7 kB/s)
Reading package lists... Done

================================================================================
================================================================================

                              DEPRECATION WARNING

  Node.js 8.x LTS Carbon is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_10.x â Node.js 10 LTS "Dubnium"
   * https://deb.nodesource.com/setup_12.x â Node.js 12 LTS "Erbium"
   * https://deb.nodesource.com/setup_14.x â Node.js 14 LTS "Fermium" (recommended)
   * https://deb.nodesource.com/setup_15.x â Node.js 15 "Fifteen"
   * https://deb.nodesource.com/setup_16.x â Node.js 16 "Gallium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...

## Populating apt-get cache...

+ apt-get update
Hit:1 http://ftp.debian.org/debian buster InRelease
Hit:2 http://ftp.debian.org/debian buster-updates InRelease
Hit:3 http://security.debian.org buster/updates InRelease
Hit:4 http://ftp.fau.de/osmc/osmc/apt buster InRelease
Hit:5 https://deb.nodesource.com/node_8.x stretch InRelease
Reading package lists... Done

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/buster/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null

## Creating apt sources list file for the NodeSource Node.js 8.x LTS Carbon repo...

+ echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_8.x buster main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_8.x buster main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.debian.org buster/updates InRelease
Hit:2 http://ftp.debian.org/debian buster InRelease
Hit:3 http://ftp.debian.org/debian buster-updates InRelease
Get:5 https://deb.nodesource.com/node_8.x buster InRelease [4619 B]
Hit:4 http://ftp.fau.de/osmc/osmc/apt buster InRelease
Get:6 https://deb.nodesource.com/node_8.x buster/main Sources [761 B]
Get:7 https://deb.nodesource.com/node_8.x buster/main armhf Packages [1006 B]
Fetched 6386 B in 3s (1972 B/s)
Reading package lists... Done

## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.20.1-2+deb10u3).
nodejs is already the newest version (14.16.1-1nodesource1).
The following packages were automatically installed and are no longer required:
  adwaita-icon-theme armv7-libass-osmc armv7-libnfs-osmc dconf-gsettings-backend dconf-service dh-python fontconfig glib-networking glib-networking-common
  glib-networking-services gnupg-agent gsettings-desktop-schemas gtk-update-icon-cache hicolor-icon-theme libaom0 libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libavcodec57 libavcodec58 libavformat57 libavutil55 libavutil56 libbind9-140 libbluray1 libcairo-gobject2 libcairo2
  libcdio13 libchromaprint1 libcodec2-0.8.1 libcolord2 libcroco3 libcryptsetup4 libdatrie1 libdconf1 libdevmapper-event1.02.1 libdns162 libdrm-common
  libdrm2 libegl-mesa0 libegl1 libegl1-mesa libenca0 libepoxy0 libevent-2.0-5 libexif12 libfile-copy-recursive-perl libflac8 libgbm1 libgdbm3
  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libglapi-mesa libglvnd0 libgme0 libgomp1 libgsm1 libgtk-3-0 libgtk-3-common libhdhomerun3 libicu57 libid3tag0
  libisc160 libisccc140 libisccfg140 libiso9660-8 libjson-glib-1.0-0 libjson-glib-1.0-common liblvm2app2.2 liblwres141 libminiupnpc10 libmp3lame0
  libmpg123-0 libncurses5 libntfs-3g871 libopenjp2-7 libopenmpt0 libopus0 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libperl5.24 libpixman-1-0
  libprocps6 libproxy1v5 libpython3.5-minimal libpython3.5-stdlib librest-0.7-0 librsvg2-2 librsvg2-common libshine3 libsnappy1v5 libsoup-gnome2.4-1
  libsoup2.4-1 libsoxr0 libspeex1 libssh-gcrypt-4 libssl1.0.2 libswresample2 libswresample3 libthai-data libthai0 libtheora0 libtwolame0 libunistring0
  libva-drm1 libva-drm2 libva-x11-1 libva-x11-2 libva1 libva2 libvdpau1 libvorbisfile3 libvpx4 libvpx5 libwavpack1 libwayland-client0 libwayland-cursor0
  libwayland-egl1 libwayland-egl1-mesa libwayland-server0 libwebpmux2 libx11-6 libx11-data libx11-xcb1 libx264-148 libx264-155 libx265-165 libx265-95
  libxau6 libxcb-dri2-0 libxcb-dri3-0 libxcb-present0 libxcb-render0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcb1 libxcomposite1 libxcursor1
  libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6 libxinerama1 libxrandr2 libxrender1 libxshmfence1 libxvidcore4 libzvbi-common libzvbi0 python-imaging
  python3-distutils python3-lib2to3 python3.5 python3.5-minimal update-inetd
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: nodejs (>= 6.11~) but it is not going to be installed
       Depends: node-abbrev (>= 1.1.1~) but it is not going to be installed
       Depends: node-ansi-regex (>= 3.0~) but it is not going to be installed
       Depends: node-ansistyles (>= 0.1.3~) but it is not going to be installed
       Depends: node-aproba (>= 1.2~) but it is not going to be installed
       Depends: node-archy (>= 1.0~) but it is not going to be installed
       Depends: node-cacache (>= 10.0.4~) but it is not going to be installed
       Depends: node-bluebird (>= 3.5.1~) but it is not going to be installed
       Depends: node-call-limit (>= 1.1~) but it is not going to be installed
       Depends: node-chownr (>= 1.0.1~) but it is not going to be installed
       Depends: node-config-chain (>= 1.1.11~) but it is not going to be installed
       Depends: node-detect-indent (>= 5.0~) but it is not going to be installed
       Depends: node-detect-newline (>= 2.1~) but it is not going to be installed
       Depends: node-editor (>= 1.0~) but it is not going to be installed
       Depends: node-fs-vacuum (>= 1.2.10~) but it is not going to be installed
       Depends: node-fs-write-stream-atomic (>= 1.0.10~) but it is not going to be installed
       Depends: node-glob (>= 7.1.2~) but it is not going to be installed
       Depends: node-graceful-fs (>= 4.1.11~) but it is not going to be installed
       Depends: node-has-unicode (>= 2.0.1~) but it is not going to be installed
       Depends: node-hosted-git-info (>= 2.6~) but it is not going to be installed
       Depends: node-iferr (>= 0.1.5~) but it is not going to be installed
       Depends: node-inflight (>= 1.0.6~) but it is not going to be installed
       Depends: node-inherits (>= 2.0.3~) but it is not going to be installed
       Depends: node-ini (>= 1.3.5~) but it is not going to be installed
       Depends: node-npm-package-arg but it is not going to be installed
       Depends: node-promzard but it is not going to be installed
       Depends: node-jsonstream (>= 1.3.2~) but it is not going to be installed
       Depends: node-json-parse-better-errors (>= 1.0.1~) but it is not going to be installed
       Depends: node-lazy-property (>= 1.0~) but it is not going to be installed
       Depends: node-libnpx (>= 10.0.1~) but it is not going to be installed
       Depends: node-lockfile (>= 1.0.3~) but it is not going to be installed
       Depends: node-lru-cache (>= 4.1.1~) but it is not going to be installed
       Depends: node-mississippi (>= 3.0~) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-move-concurrently (>= 1.0.1~) but it is not going to be installed
       Depends: node-nopt but it is not going to be installed
       Depends: node-normalize-package-data (>= 2.4~) but it is not going to be installed
       Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
       Depends: node-resolve-from (>= 4.0~) but it is not going to be installed
       Depends: node-encoding but it is not going to be installed
       Depends: node-errno but it is not going to be installed
       Depends: node-npmlog (>= 4.1.2~) but it is not going to be installed
       Depends: node-once (>= 1.4~) but it is not going to be installed
       Depends: node-opener (>= 1.4.3~) but it is not going to be installed
       Depends: node-osenv (>= 0.1.5~) but it is not going to be installed
       Depends: node-path-is-inside (>= 1.0.2~) but it is not going to be installed
       Depends: node-promise-inflight (>= 1.0.1~) but it is not going to be installed
       Depends: node-ansi but it is not going to be installed
       Depends: node-qw (>= 1.0.1~) but it is not going to be installed
       Depends: node-read (>= 1.0.7~) but it is not going to be installed
       Depends: node-read-package-json (>= 2.0.13~) but it is not going to be installed
       Depends: node-request (>= 2.83~) but it is not going to be installed
       Depends: node-retry (>= 0.10.1~) but it is not going to be installed
       Depends: node-rimraf (>= 2.6.2~) but it is not going to be installed
       Depends: node-safe-buffer (>= 5.1.1~) but it is not going to be installed
       Depends: node-semver (>= 5.5~) but it is not going to be installed
       Depends: node-sha (>= 2.0.1~) but it is not going to be installed
       Depends: node-slide (>= 1.1.6~) but it is not going to be installed
       Depends: node-sorted-object (>= 2.0.1~) but it is not going to be installed
       Depends: node-from2 but it is not going to be installed
       Depends: node-stream-iterate but it is not going to be installed
       Depends: node-ssri (>= 5.2.4~) but it is not going to be installed
       Depends: node-strip-ansi (>= 4.0~) but it is not going to be installed
       Depends: node-tar (>= 4.4~) but it is not going to be installed
       Depends: node-text-table (>= 0.2~) but it is not going to be installed
       Depends: node-uid-number (>= 0.0.6~) but it is not going to be installed
       Depends: node-unique-filename (>= 1.1~) but it is not going to be installed
       Depends: node-unpipe (>= 1.0~) but it is not going to be installed
       Depends: node-boxen (>= 1.2.1~) but it is not going to be installed
       Depends: node-import-lazy but it is not going to be installed
       Depends: node-is-npm (>= 1.0~) but it is not going to be installed
       Depends: node-latest-version (>= 3.0~) but it is not going to be installed
       Depends: node-semver-diff (>= 2.0~) but it is not going to be installed
       Depends: node-xdg-basedir (>= 3.0~) but it is not going to be installed
       Depends: node-validate-npm-package-name (>= 3.0~) but it is not going to be installed
       Depends: node-which (>= 1.3~) but it is not going to be installed
       Depends: node-wrappy (>= 1.0.2~) but it is not going to be installed
       Depends: node-write-file-atomic (>= 2.3~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
/usr/bin/tsc -> /usr/lib/node_modules/typescript/bin/tsc
/usr/bin/tsserver -> /usr/lib/node_modules/typescript/bin/tsserver
+ typescript@4.2.4
updated 1 package in 12.077s
Cloning into 'digionline'...
remote: Enumerating objects: 548, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 548 (delta 44), reused 71 (delta 36), pack-reused 462
Receiving objects: 100% (548/548), 154.07 KiB | 2.14 MiB/s, done.
Resolving deltas: 100% (328/328), done.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> fmerge@1.2.0 install /home/osmc/digionline/node_modules/fmerge
> node install.js

internal/fs/utils.js:307
    throw err;
    ^

Error: EACCES: permission denied, open 'fmerge.min.js'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at Object.<anonymous> (/home/osmc/digionline/node_modules/fmerge/install.js:19:4)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: 'fmerge.min.js'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fmerge@1.2.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fmerge@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-29T07_01_34_428Z-debug.log
Kerlek add meg bejelentkezesi adataidat... (Egy pillanat es nyilik a szerkeszto. Mentes: CTRL+X)
Created symlink /etc/systemd/system/multi-user.target.wants/digionline.service -> /etc/systemd/system/digionline.service.
Hit:1 http://security.debian.org buster/updates InRelease
Hit:2 http://ftp.debian.org/debian buster InRelease
Hit:3 http://ftp.debian.org/debian buster-updates InRelease
Hit:4 https://deb.nodesource.com/node_8.x buster InRelease
Hit:5 http://ftp.fau.de/osmc/osmc/apt buster InRelease
Reading package lists... Done
Running apt-get upgrade on your system can cause adverse effects on your system
Use apt-get dist-upgrade, which is the proper way to administer a Debian / Ubuntu system
For more information about updates, see https://osmc.tv/wiki/general/keeping-your-osmc-system-up-to-date/
A telepĂ­tĹ lefutott, ĂşjraindĂ­tĂĄs szĂźksĂŠges
Akarod most ĂşjraindĂ­tani a rendszert? [I/N]i

**Comment by pappt** [comment]
Megoldódott ez a hiba.

Első lépésben az npm-et ezzel telepítettem: https://npmjs.org/install.sh

utána az osmc_installer.sh-ból kiszedtem ezt a két sort:
apt-get install -y npm
npm install typescript -g

ezután lefutott a telepítés hiba nélkül, legenerálódott az m3u8 file is.

**Comment by szabbenjamin** [comment]
Köszi! Sajna az a tapasztalatom, hogy a régebbi raspi-ken már nem telepíthető az újabb node, illetve npm verzió, mindenesetre bele rakom a telepítőbe a megoldásod hátha képes fallback-elni. :)

**Comment by pepev82** [comment]
> Megoldódott ez a hiba.
> 
> Első lépésben az npm-et ezzel telepítettem: https://npmjs.org/install.sh
> 
> utána az osmc_installer.sh-ból kiszedtem ezt a két sort: apt-get install -y npm npm install typescript -g
> 
> ezután lefutott a telepítés hiba nélkül, legenerálódott az m3u8 file is.

Szia!

Ha megkérlek csinálsz egy image-t az sd kártyádról - ha még használod persze, mert nekem sehogy sem akar sikerülni az új telepítés RPi 3b+-ra ?

Köszönöm!

**Comment by pappt** [comment]
Szia, már nem használom egy jó ideje, le is szedtem a pi-ről

**Comment by pepev82** [comment]
> 

Ok, azért köszönöm válaszod.

**Comment by szabbenjamin** [comment]
rpi3-asom nekem sincsen, sajnos már csak 4-es raspi maradt - láthatóan olyan mértékben fogynak az ezek az eszközök, hogy lassan más platform irányába kell sajnos nézelődnünk.
Ránézésre egyébként a régi node, vagy régi OS miatt lehet, ránézek mit lehetne vele kezdeni. Node upgrade például simán beleférne.

**Comment by pepev82** [comment]
> rpi3-asom nekem sincsen, sajnos már csak 4-es raspi maradt - láthatóan olyan mértékben fogynak az ezek az eszközök, hogy lassan más platform irányába kell sajnos nézelődnünk. Ránézésre egyébként a régi node, vagy régi OS miatt lehet, ránézek mit lehetne vele kezdeni. Node upgrade például simán beleférne.

Szia!

Köszönöm, a válaszod, és a munkád is ezzel a servlet-tel.

Raspi 3b+ -ra most (nyílván kínosan hosszú idő alatt) de felment az Ubuntu 22.04.1.
Ezen szépen fut a servlet, de néha kiáll egy ilyen hibára:

Tue Jan 03 2023 19:01:49 GMT+0100 (Central European Standard Time) [ 'GET channel 266' ]
Tue Jan 03 2023 19:01:50 GMT+0100 (Central European Standard Time) [ 'loaded from request', 'id_266' ]
/home/ubi/digionline/lib/digionline.js:275
                    'User-Agent': this.userAgent
                                       ^

TypeError: Cannot read property 'userAgent' of undefined
    at searchChannel (/home/ubi/digionline/lib/digionline.js:275:40)
    at /home/ubi/digionline/lib/digionline.js:251:25
    at Request._callback (/home/ubi/digionline/lib/common.js:26:17)
    at Request.self.callback (/home/ubi/digionline/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/ubi/digionline/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/ubi/digionline/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
root@ubi:/home/ubi/digionline#

Egy npm start után újra szépen megy.

Ezt a hibát mi okozhatja ?

Van ugye, a másik hiba amikor "nincs meg a csatorna", de ezen nem áll ki hibára a servlet, várakozással vagy csatorna váltással megoldódik.

(Kodit nem telepítettem erre az RPi3-ra, nem tudom, megbírná-e?
Nálam 3 db 12 éves android boxot szolgál ki szerverként az RPi3-on futó servlet, amiken LibreELEC - Kodi fut.)

Üdv!

**Comment by szabbenjamin** [comment]
Köszi a hibajelzést, javítom.
Addig tedd be systemctl-be, hogy service-ként újraindulhasson ha hibával kilépett.
