### ISSUE TITLE
Néhány közszolgálati csatorna időszakos betöltési hibája

### ISSUE THREAD

**Issue by szabbenjamin** [szabbenjamin/digionline#6]
```
Sat Jun 02 2018 16:53:09 GMT+0200 (CEST) # Nem talalhato ilyen stream, vagy nem mukodik a csatorna: M2 (lqsdf)
Sat Jun 02 2018 16:53:09 GMT+0200 (CEST) # Inditom helyette ezt: http://dostr.digi.hu/stream.m3u8?c=93&q=hq&id=47a91f0f4fbb03dd77ebe3e6d3797a70f297d66b89da1d48f5ac1abd51f417a6&_t=1527951189
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=40,BANDWIDTH=2500128,AVERAGE-BANDWIDTH=2500128,RESOLUTION=1280x768,NAME="hd"
http://dostr.digi.hu/stream.m3u8?c=93&q=hq&id=47a91f0f4fbb03dd77ebe3e6d3797a70f297d66b89da1d48f5ac1abd51f417a6&_t=1527951189


events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

```

Valószínűleg egyszerűen nem működik a stream, hibakezelés szükséges

**Comment by szabbenjamin** [comment]
Rosszul voltak lekezelve a csatorna url-jei. A hiba javítva lett itt: https://github.com/szabbenjamin/digionline/commit/76daac73d45a40f7b507347be1226aee23db4b76
